apiVersion: v1
kind: Pod
metadata:
  name: terminal-{{USER_ID}}
  namespace: {{NAMESPACE}}
spec:
  containers:
  - name: terminal
    image: {{IMAGE}}
    command: ["/bin/bash", "-c", "sleep infinity"]
    env:
    - name: MOODLE_USER
      value: "{{USER_ID}}"
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000