apiVersion: v1
kind: ServiceAccount
metadata:
  name: moodle-terminal
  namespace: {{NAMESPACE}}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{NAMESPACE}}
  name: pod-manager
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec"]
  verbs: ["create", "delete", "get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: moodle-terminal-binding
  namespace: {{NAMESPACE}}
subjects:
- kind: ServiceAccount
  name: moodle-terminal
  namespace: {{NAMESPACE}}
roleRef:
  kind: Role
  name: pod-manager
  apiGroup: rbac.authorization.k8s.io